apiVersion: apps/v1
kind: Deployment
metadata:
  name: meecha-location
  namespace: meecha
spec:
  replicas: 5
  selector:
    matchLabels:
      app: meecha-location
  template:
    metadata:
      labels:
        app: meecha-location
    spec:
      containers:
        - name: meecha-location
          image: ghcr.io/meecha-org/meecha_back/meecha-location:latest
          ports:
            - containerPort: 8090
          resources:
            requests:
              cpu: "100m"    # 例：100ミリコア
              memory: "128Mi"
            limits:
              cpu: "500m"    # 例：500ミリコア
              memory: "256Mi"
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: meechasecret
                  key: RedisHost

            - name: GRPC_SERVER
              valueFrom:
                secretKeyRef:
                  name: meechasecret
                  key: GrpcServer

            - name: SessionSecret
              valueFrom:
                secretKeyRef:
                  name: meechasecret
                  key: SessionSecret

            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: meechasecret
                  key: AppdbDSN

            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: meechasecret
                  key: JwtPublicKey
  
---
apiVersion: v1
kind: Service
metadata:
  name: meecha-location-svc
  namespace: meecha
spec:
  type: LoadBalancer
  selector:
    app: meecha-location
  ports:
  - port: 8090
    targetPort: 8090
    