apiVersion: apps/v1
kind: Deployment
metadata:
  name: meecha-redis
  namespace: meecha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meecha-redis
  template:
    metadata:
      labels:
        app: meecha-redis
    spec:
      containers:
        - name: meecha-redis
          image: redis:latest
          ports:
            - containerPort: 6379
  
---
apiVersion: v1
kind: Service
metadata:
  name: meecha-redis-svc
  namespace: meecha
spec:
  type: LoadBalancer
  selector:
    app: meecha-redis
  ports:
  - port: 6379
    targetPort: 6379